### ISSUE TITLE
Roll for Initiative fails in Foundry v10

### ISSUE THREAD

**Issue by Aelphais** [HavlockV/CoC7-FoundryVTT#1232]
The roll for initiative buttons fail to operate under standard CoC7 rule set (By which I mean dex==initiative. I have not tried the optional rule for actually rolling initiative).

### Prerequisites.

- [ X ] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [ X ] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

Clicking Roll All and Roll NPCs simply causes the two buttons to disappear with no other alterations to the encounter table. Clicking the large dice icon next to the actors fails to do anything at all. However, clicking the Reset Initiative button seems to make it function as normal.

## Expected Behavior.

Numbers should appear.

## Actual Behavior.

Nothing happens.

## Error Log

```
combat.js:134
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at Combat.rollInitiative (combat.js:134:1)
    at Combat.rollAll (foundry.js:18551:17)
    at CombatTracker._onCombatControl (foundry.js:74043:36)
    at HTMLAnchorElement.<anonymous> (foundry.js:73980:51)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

combat.js:134 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at Combat.rollInitiative (combat.js:134:1)
    at Combat.rollNPC (foundry.js:18565:17)
    at CombatTracker._onCombatControl (foundry.js:74043:36)
    at HTMLAnchorElement.<anonymous> (foundry.js:73980:51)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

combat.js:134 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at Combat.rollInitiative (combat.js:134:1)
    at CombatTracker._onCombatantControl (foundry.js:74075:23)
    at HTMLAnchorElement.<anonymous> (foundry.js:73983:54)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

combat.js:134
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at Combat.rollInitiative (combat.js:134:1)
    at CombatTracker._onCombatantControl (foundry.js:74075:23)
    at HTMLAnchorElement.<anonymous> (foundry.js:73983:54)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

**Comment by snap01** [comment]
A fix for this should be included in the next release
