### ISSUE TITLE
Dhole's House json Importer Fails for Foundry v10

### ISSUE THREAD

**Issue by Dick-K** [HavlockV/CoC7-FoundryVTT#1239]
On Foundry v10, attempting to import a Dhole's House json fails to create an actor. See console error below.

- [Y] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [Y] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.
As title

## Expected Behavior.

An actor should be created in an Imported Actors folder.

## Actual Behavior.

No actor created

## Screenshots.

Console Error - note same json works for v9.

Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'skillName')
    at CoC7DholeHouseActorImporter.extractSkills (dholehouse_importer.js:170:1)
    at async CoC7DholeHouseActorImporter.convertDholeHouseCharacterData (dholehouse_importer.js:116:1)
    at async CoC7DholeHouseActorImporter.createNPCFromDholeHouse (dholehouse_importer.js:322:1)
    at async CoC7ActorImporterDialog._onClickSubmit (actor-importer-dialog.js:165:1)

**Comment by snap01** [comment]
A fix for this should be included in the next release

**Comment by snap01** [comment]
Can you please confirm if this issue can be closed with the latest 0.9.1 release?

**Comment by Dick-K** [comment]
Yes, all good now, thanks a lot for fixing and following-up.
