### ISSUE TITLE
Dice So Nice Clashing With Roll Cards 

### ISSUE THREAD

**Issue by Cactus88888** [HavlockV/CoC7-FoundryVTT#1654]
After freshly installing a new version of Foundry, adding the Coc 7e game system, and Dice So Nice from the modules tab I went into a fresh world and was able to have the Sanity Encounter mechanic work without Dice So Nice, once its 3D dice were enabled however the Sanity Encounter mechanic refused to roll dice, clicking the chat card would do nothing and the console would show the error:

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at CoC7Dice.showRollDice3d (dice.js:92:27)
    at CoC7Check._perform (check.js:809:22)
    at async SanCheckCard.rollSan (san-check.js:260:62)
    at async CoC7Chat._onChatCardAction (chat.js:1096:51)
showRollDice3d @ dice.js:92
_perform @ check.js:809
await in _perform (async)
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

## Browser and OS
Foundry's Desktop App Latest Version on the Windows OS

**Comment by snap01** [comment]
Using the following steps the process seems to work, can you please let us know how you are replicating the issue?
* On a clean world
* Enabling Dice So Nice module
* Create a new Scene
* Import from Compendium "System Examples | en" -> "Examples" -> "1920 Character" by dragging onto the scene
* Click "Create Link"
* Type = Sanity check, 1, 6, test
* Send to chat
* Select token
* Roll works

or

* On a clean world
* Enabling Dice So Nice module
* Create a new Scene
* Import from Compendium "System Examples | en" -> "Examples" -> "1920 Character" by dragging onto the scene
* Import from Compendium "System Examples | en" -> "Examples" -> "Creature example" by dragging onto the scene
* Open "Creature example" sheet
* Target "1920 Character"
* Click "Sanity Loss"
* Roll works

**Comment by Cactus88888** [comment]
> Using the following steps the process seems to work, can you please let us know how you are replicating the issue?
> 
> * On a clean world
> * Enabling Dice So Nice module
> * Create a new Scene
> * Import from Compendium "System Examples | en" -> "Examples" -> "1920 Character" by dragging onto the scene
> * Click "Create Link"
> * Type = Sanity check, 1, 6, test
> * Send to chat
> * Select token
> * Roll works
> 
> or
> 
> * On a clean world
> * Enabling Dice So Nice module
> * Create a new Scene
> * Import from Compendium "System Examples | en" -> "Examples" -> "1920 Character" by dragging onto the scene
> * Import from Compendium "System Examples | en" -> "Examples" -> "Creature example" by dragging onto the scene
> * Open "Creature example" sheet
> * Target "1920 Character"
> * Click "Sanity Loss"
> * Roll works

**Comment by Cactus88888** [comment]
Foundry V12 Build 331
Dice So Nice Version 5.1.4
- Moved old data folder for safety and then deleted the foundry pathway folder
- Reinstall a clean version of Foundry from the wizard on the Foundry website for Windows OS
- Download Dice So Nice V 5.1.4
- Download CoC7e system
- Open the first world on this installation, name it "w" and load in as the Gamemaster
- Open a scene, using default settings
- Import 1920s Character from Compendium
- Open sheet or use the link creation tool to make a sanity check with min 1 max 6 named "test"
- The card sends to chat, when clicked as GM does nothing and doesn't produce anything in the console
- Select token then click card, red error as seen above appears in F12 console
- Import a creature, target investigator and clicking san loss, card still does not function and produces same error in chat

**Comment by Cactus88888** [comment]
The F12 Error also has a yellow warning I did not see until now that reads:

Error: The async option for Roll#evaluate has been removed. Use Roll#evaluateSync for synchronous roll evaluation.
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at Roll.evaluate (foundry-esm.js:63561:23)
    at Roll.roll (foundry-esm.js:63742:19)
    at CoC7Dice.roll (dice.js:37:9)
    at CoC7Check._perform (check.js:803:23)
    at SanCheckCard.rollSan (san-check.js:261:25)
    at CoC7Chat._onChatCardAction (chat.js:1097:24)
    at HTMLElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)

**Comment by snap01** [comment]
Could you please compress the folder w from your worlds Data folder and attach it to this issue?

**Comment by Cactus88888** [comment]
[the-dreary-night - Copy.zip](https://github.com/user-attachments/files/18171117/the-dreary-night.-.Copy.zip)

Strange advancement, through Molten Hosting using their service and opening the Foundry Browser version, the above steps of simply making one scene with the one module works and the SAN rolls work and 3D dice appear, super strange. 

EDIT: My own newly created worlds also work properly on the browser, it is just the desktop app that produces that console issue

**Comment by snap01** [comment]
I'm still unable to replicate this with your world, as it is only happening with the Windows Foundry Application it may be a setting in your localStorage that is causing a conflict.

In the debug console, on the Application tab, Storage, Local storage, <your local address>. You should see several key value pairs, you can make a note of them and clear them down, to see if that fixes it.

In the Console tab to add any you want back in manually until you find the cause
localStorage.setItem('KEY', VALUE);
e.g.
localStorage.setItem('core.tourProgress', {"core":{"backupsOverview":0}});
